### ISSUE TITLE
sh_barrels_minigame issue / improvements

### ISSUE THREAD

**Issue by Alf21** [ZacharyHinds/ttt2mg-randomat#10]
https://github.com/ZacharyHinds/ttt2mg-randomat/blob/8b6b24f6d0eb77557ad349762c4fe67493d3aaae/lua/minigames/minigames/sh_barrels_minigame.lua#L47
I suggest not using `ipairs` but a default for-loop instead.

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/8b6b24f6d0eb77557ad349762c4fe67493d3aaae/lua/minigames/minigames/sh_barrels_minigame.lua#L49
Additionally, you making a non-iterable list. Instead, you should use:
```lua
      plys[#plys + 1] = ply
```
Otherwise, this line https://github.com/ZacharyHinds/ttt2mg-randomat/blob/8b6b24f6d0eb77557ad349762c4fe67493d3aaae/lua/minigames/minigames/sh_barrels_minigame.lua#L53 wouldn't work, because `ipairs` will break if the list isn't iterable. Even here, I suggest using a default for-loop like you did here https://github.com/ZacharyHinds/ttt2mg-randomat/blob/8b6b24f6d0eb77557ad349762c4fe67493d3aaae/lua/minigames/minigames/sh_barrels_minigame.lua#L55.

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/8b6b24f6d0eb77557ad349762c4fe67493d3aaae/lua/minigames/minigames/sh_barrels_minigame.lua#L54
You don't need to check the players on certain conditions again if the players that are on the list have been checked already.

---

This line https://github.com/ZacharyHinds/ttt2mg-randomat/blob/8b6b24f6d0eb77557ad349762c4fe67493d3aaae/lua/minigames/minigames/sh_barrels_minigame.lua#L56 stops the client from executing the code. I suggest putting it in front of the for-loop to save performance (you don't have to go into several loops if you don't plan to execute any commands in there).

---

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/8b6b24f6d0eb77557ad349762c4fe67493d3aaae/lua/minigames/minigames/sh_barrels_minigame.lua#L60
Using a `return` in a for-loop will break the loop and exit the function. If that isn't planned, I suggest using `continue`.

---

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/8b6b24f6d0eb77557ad349762c4fe67493d3aaae/lua/minigames/minigames/sh_barrels_minigame.lua#L63
Static vars should be defined outside for-loops to save performance.

---

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/8b6b24f6d0eb77557ad349762c4fe67493d3aaae/lua/minigames/minigames/sh_barrels_minigame.lua#L44
This function is just called on server-side, so I suggest putting it into the if-clause below or everything into the else-part above.

**Comment by ZacharyHinds** [comment]
I've made the changes you've recommended, thanks!
