### ISSUE TITLE
Bee minigame, bad while-loop, etc.

### ISSUE THREAD

**Issue by Alf21** [ZacharyHinds/ttt2mg-randomat#11]
https://github.com/ZacharyHinds/ttt2mg-randomat/blob/a2f6e73cc9120ac19a091f9f28b31289e5c491a2/lua/minigames/minigames/sh_bees_minigame.lua#L45
Here I suggest a better solution because the later the minigame is activated, the more `not alive` players will exist, and the longer the loop will take (in bad cases very long, based on the random-seed, etc.).

Therefore, I suggest a way better solution: remove the player that isn't alive or Spec anymore from the list, probably in the while loop, and then check in the while loop whether the list is empty (shouldn't happen theoretically, but it's endless-loop-critically).

---

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/a2f6e73cc9120ac19a091f9f28b31289e5c491a2/lua/minigames/minigames/sh_bees_minigame.lua#L44-L45
Additionally, directly accessing a player in a timed function that was previously stored in a list created outside the timed function is critical too. Timed functions are run async / separately and are in certain cases queued. They don't run at the exact time you defining them to be run. And even in that time (+ the additional time in the queue/processing time), the "cached" player can disconnect. As result, the `Alive()` and the `IsSpec()` function CAN (and gonna) fail. Here, it's recommended doing a `IsValid` check before trying to access any functions on this player "object".

---

If you wanna write a nice add-on, you should take care of your used environment. Which functions should be global, which shouldn't?
https://github.com/ZacharyHinds/ttt2mg-randomat/blob/a2f6e73cc9120ac19a091f9f28b31289e5c491a2/lua/minigames/minigames/sh_bees_minigame.lua#L27
That definitely shouldn't be global

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/a2f6e73cc9120ac19a091f9f28b31289e5c491a2/lua/minigames/minigames/sh_bees_minigame.lua#L28
Here I don't see any sense for making it global too

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/a2f6e73cc9120ac19a091f9f28b31289e5c491a2/lua/minigames/minigames/sh_bees_minigame.lua#L49
And that definitely shouldn't be global

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/a2f6e73cc9120ac19a091f9f28b31289e5c491a2/lua/minigames/minigames/sh_bees_minigame.lua#L41
That don't need to be cached, because it's just used once

---

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/a2f6e73cc9120ac19a091f9f28b31289e5c491a2/lua/minigames/minigames/sh_bees_minigame.lua#L53
Here

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/a2f6e73cc9120ac19a091f9f28b31289e5c491a2/lua/minigames/minigames/sh_bees_minigame.lua#L50
And here you never check whether those "objects" are valid compared with your other minigames.

---

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/a2f6e73cc9120ac19a091f9f28b31289e5c491a2/lua/minigames/minigames/sh_bees_minigame.lua#L63
shouldn't the created bees getting destroyed here (if still alive?) - thinking about a possibility to deactivate the minigame before the game ends, e.g. with a jamming item, etc.

**Comment by ZacharyHinds** [comment]
I believe that I've fixed all these issues, but let me know if you notice anything that's still a problem

**Comment by Alf21** [comment]
https://github.com/ZacharyHinds/ttt2mg-randomat/blob/3aea4f29f00fae1f40dfbe3801bcb1467650548f/lua/minigames/minigames/sh_bees_minigame.lua#L55
Here you could store `#plys`, but if doing so, you need to decrease the amount if removing an entry from the list as well, so it's not necessary all in all. Just a hint for future changes, you can ignore this comment.

---
https://github.com/ZacharyHinds/ttt2mg-randomat/blob/3aea4f29f00fae1f40dfbe3801bcb1467650548f/lua/minigames/minigames/sh_bees_minigame.lua#L57

```lua
while not IsValid(ply) or not ply:Alive() and ply:IsSpec() and #plys > 0 do
```
should be
```lua
while (not IsValid(ply) or not ply:Alive() and ply:IsSpec()) and #plys > 0 do
```

But some lines below, I suggest another solution.

---

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/3aea4f29f00fae1f40dfbe3801bcb1467650548f/lua/minigames/minigames/sh_bees_minigame.lua#L31
`RemovePly` function is useless theoretically, but definitely bad for the performance.
Instead, you could simply try using https://wiki.facepunch.com/gmod/table.remove here https://github.com/ZacharyHinds/ttt2mg-randomat/blob/3aea4f29f00fae1f40dfbe3801bcb1467650548f/lua/minigames/minigames/sh_bees_minigame.lua#L58-L59 .

I would do it that way, additionally to prevent multiple bee spawning for the same player (because you don't modify the list every time):
```lua
local ply

repeat
    if #plys <= 0 then return end -- this will break the loop and exit the timer

    local rnd = math.random(#plys)
    ply = plys[rnd]
    table.remove(plys, rnd)
until IsValid(ply) and ply:Alive() and not ply:IsSpec()
```

---

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/3aea4f29f00fae1f40dfbe3801bcb1467650548f/lua/minigames/minigames/sh_bees_minigame.lua#L65-L73

`headBee:SetHealth(1000)` should be placed directly below `headBee:SetNPCState(2)` because even if the "Bee" (prop_dynamic) isn't valid (just the appearance of a bee), the functionality is still given.

---

https://github.com/ZacharyHinds/ttt2mg-randomat/blob/3aea4f29f00fae1f40dfbe3801bcb1467650548f/lua/minigames/minigames/sh_bees_minigame.lua#L81
Here you cleaning up every manhack. Instead, you should put your created manhacks directly into a list on creation. And then, if they are still valid, destroy them in the cleanup function.
